### ISSUE TITLE
gmail bug

### ISSUE THREAD

**Issue by gilesorr** [ardagnir/pterosaur#19]
2014-11-25:                                                                     
FF v33.0                                                                        
latest vimbed                                                                   
latest Pentadactyl nightly build (Pentadactyl's stable build only goes up       
to  FF v30)                                                                     
latest Pterosaur                                                                
Ubuntu 14.04 "Trusty"                                                           
                                                                                
Backspace in gmail editor in insert mode (almost?) always causes cursor to reset to 1,1 position (top left corner of the editor).  Not having that problem with the github issue tracker window, although it's driving the load through the roof on an unloaded i7 and it's still extremely laggy.

**Comment by ardagnir** [comment]
Both the gmail backspace bug and the performance problems should be fixed in the unstable 0.9 branch. Even if they are, I'll be leaving this bug open until 0.9 becomes stable.

**Comment by ardagnir** [comment]
Pterosaur has been updated to 1.0. This bug should be fixed in master now.
