### ISSUE TITLE
Unable to enter non-ascii characters

### ISSUE THREAD

**Issue by TristramShandy** [ardagnir/pterosaur#29]
When I switch to a german keyboard and enter any of the non-standard characters like äöüß things get weird: Pterosaur does not display any character, but after hitting escape the non-standard character is displayed. However none of the other characters I may have hit in between are shown. When I do this on Google, the previews seem to react to all the characters I enter. In the debug terminal none of the special characters is ever displayed.

This is on Linux with a brand new vimbed and Firefox 35.0.1

**Comment by geier** [comment]
It's the same with vimperator.

**Comment by ardagnir** [comment]
Fixed in 1.1

**Comment by TristramShandy** [comment]
Thanks man,

yöü röck!

Cheers, Michael

2015-03-07 1:46 GMT+01:00 ardagnir <notifications@github.com>:
