### ISSUE TITLE
Text doesn't show up in textfield in firefox

### ISSUE THREAD

**Issue by vexxor** [ardagnir/pterosaur#30]
Firefox: 35.0.1

I've tried disabling all other addons and just using pterosaur with same effects, but fwiw I run a pentadactyl that I build from source ( last build a couple of days ago ).

When i enabled debugging for pterosaur, I can see a vim instance in my terminal and what I'm typing, but cannot see anything in firefox itself.

Any idea what I'm doing wrong?

**Comment by ardagnir** [comment]
What OS/vim version are you using? Do you see any errors in the browser console (Control-Shift-J)? What happens when you type vim --serverlist?

**Comment by vexxor** [comment]
OS: Linux ( Arch Linux updated weekly, so more or less up to date )
Vim: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb  4 2015 08:02:36)

vim --serverlist returns nothing

I've disabled all addons except pterosaur and the js console doesn't seem to hold anything relevant ( posting just in case )


Failed to load native module at path '/usr/lib/firefox/components/libxpcomsample.so': (80004005) /usr/lib/firefox/components/libxpcomsample.so: cannot open shared object file: No such file or directory
Could not read chrome manifest 'file:///usr/lib/firefox/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.
While creating services from category 'profile-after-change', could not create service for entry 'MobileConnection Service', contract ID '@mozilla.org/mobileconnection/mobileconnectionservice;1'
1424423953241	Services.HealthReport.HealthReporter	WARN	Saved state file does not exist.
1424423953241	Services.HealthReport.HealthReporter	WARN	No prefs data found.

**Comment by ardagnir** [comment]
What does "`vim --version | grep clientserver`" return? If you get "-clientserver", you can use pacman's "gvim" package which should come with a vim with +clientserver support.

Also, can you try just running "`vim --servername test`" in one terminal and "`vim --serverlist`" in another?

**Comment by vexxor** [comment]
```
[vx@batmobile ~]$ vim --version | grep clientserver
+clientserver    -hangul_input    +netbeans_intg   +title

[vx@batmobile ~]$ vim --serverlis
TEST
```

It may have been unclear in my first post, but when i turned on pterosaur debugging I could see a vim instance in my terminal getting the text I wrote. On the firefox side, the text box just didn't display any text. This is the reason I disabled all other addons, suspecting something was clashing ( like pentadactyl, etc ).

**Comment by ardagnir** [comment]
The debugtty option uses a pipe. It doesn't require +clientserver. If you see text there, but don't see anything in vim --serverlist, it's almost certainly a clientserver problem.

Can you run `ps -e e | grep pterosaur` and then run `vim --servername test` with the same binary and all those env variables copy pasted in front? Does it still show up in serverlist? (Should look something like `TERM=foo DISPLAY=bar FOO=bar /foo/bar/vim --servername test`)

**Comment by nitishch** [comment]
I have a similar problem. If I enable this addon and put the cursor in a text field, Firefox hangs(it doesn't even load the webpage completely) and I have to force close it. I put the line `so ~/pterosaur/content/vimbed/plugin/vimbed.vim` in my `.vimrc`. 

Output of `vim --version | grep clientserver`

    +clientserver    -hangul_input    +netbeans_intg   +title

Any ideas why this might happen?

**Comment by vexxor** [comment]
Cleanup.
