### ISSUE TITLE
Return key weirdness

### ISSUE THREAD

**Issue by nihlaeth** [ardagnir/pterosaur#39]
I got pterosaur working with X11 forwarding, and everything seems fine except that my return key isn't functioning as I'd expect.

In normal mode, the return key functions, but in insert mode, it does nothing. I temporarily fixed this by adding a "inoremap \n <CR>" to my .pterosaurrc, but that's not very practical.

I've tried loading my regular .vimrc instead of .pterosaurrc, but it made no difference. Likewise, if I start vim from the command line, the return key functions just fine.

Another issue is that the return key no longer sends forms. It would only be a bit impractical, except that some sites (like facebook) do not offer actual buttons you can press, you HAVE to press return while still in the text field.

**Comment by ardagnir** [comment]
Can you reproduce the problem in pterosaur 1.1.1? Pentadactyl changed their mapping code recently, which broke return in pentadactyl+pterosaur. I've added a patch to fix this in 1.1.

**Comment by nihlaeth** [comment]
Problem seems resolved in 1.1.1, thanks!

On a slightly different note, the env overrides work! It turns out the DISPLAY var does not need to be overridden, only XAUTHORITY. My guess is that the '~' sign is the troublemaker there, given an absolute path, it works.
