### ISSUE TITLE
Return key does not work when placing facebook comments

### ISSUE THREAD

**Issue by nihlaeth** [ardagnir/pterosaur#40]
I've narrowed the problem down considerably. The return key now functions as expected in version 1.1.1, except with facebook.

When I press return after typing in the text field of the duckduckgo search engine, it activates the form as expected. 

When I press return after typing a comment on facebook, nothing happens. I've tried switching to normal mode and pressing enter then, but that does not work either. Pressing shift+enter in insert mode does output a newline.

I'm inclined to view this as a feature, but thought you might like to know ;)

**Comment by ardagnir** [comment]
The return problem should *actually* be fixed in 1.1.2. Facebook comments will have other problems though, since pterosaur can't complete with the excessive amount of javascript they use. Using facebook is the one time I disable pterosaur.
