### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by akarl** [ardagnir/pterosaur#45]
I'm not sure if Neovim has support for clientserver, it does not show up in `$ nvim --version`. I have tried googling but I only found that Neovim should be installed with all features automatically. I could just rebuild my Vim 7 if it won't work though :)

**Comment by chpill** [comment]
Neovim does not have the `clientserver` mode of vim, because it exposes a more featured msgpack-rpc API to interact with it.

Would be great to see support for that in pterausor!

**Comment by akarl818** [comment]
Alright, thanks!

**Comment by aandrieiev** [comment]
Assuming pterosaur uses vimbed for communicating with the server, perhaps this is something to ask for support of here: https://github.com/ardagnir/vimbed.git

**Comment by braham-snyder** [comment]
relevant neovim issue: https://github.com/neovim/neovim/issues/1750

as of now, https://github.com/mhinz/neovim-remote is a "temporary solution"
